//
// Generated by I18nSyncTask on Tue Feb 10 07:28:12 PST 2026

package com.threerings.sling.gwt.client;

public interface ClientMessages extends com.google.gwt.i18n.client.Messages
{
    @Key("chatHistoryLabel")
    String chatHistoryLabel ();

    @Key("postNoteLink")
    String postNoteLink ();

    @Key("statusLabel")
    String statusLabel ();

    @Key("addNewFaqQuestion")
    String addNewFaqQuestion ();

    @Key("hourHdr")
    String hourHdr ();

    @Key("relatedAccounts")
    String relatedAccounts ();

    @Key("averageEventVolume")
    String averageEventVolume ();

    @Key("accountsMatchingEmail")
    String accountsMatchingEmail (String arg0);

    @Key("familySubscriber")
    String familySubscriber ();

    @Key("eventTypeSupportAction")
    String eventTypeSupportAction ();

    @Key("noFlags")
    String noFlags ();

    @Key("frequentlyAskedQuestions")
    String frequentlyAskedQuestions ();

    @Key("link")
    String link ();

    @Key("createAccount")
    String createAccount ();

    @Key("matchesTerms")
    String matchesTerms ();

    @Key("altName")
    String altName ();

    @Key("generating")
    String generating ();

    @Key("averageEventVolumeTitle")
    String averageEventVolumeTitle ();

    @Key("errNoFilters")
    String errNoFilters ();

    @Key("postReplyTitle")
    String postReplyTitle (String arg0, String arg1);

    @Key("messages")
    String messages ();

    @Key("relAccAccountHdr")
    String relAccAccountHdr ();

    @Key("postNoteTitle")
    String postNoteTitle (String arg0, String arg1);

    @Key("showGameNames")
    String showGameNames ();

    @Key("brokenLinkOrSomething")
    String brokenLinkOrSomething ();

    @Key("ipAddress")
    String ipAddress ();

    @Key("isMoreThan")
    String isMoreThan ();

    @Key("firstResponseLabel")
    String firstResponseLabel ();

    @Key("accountNotFound")
    String accountNotFound (String arg0);

    @Key("hoursItem")
    String hoursItem ();

    @Key("eventTypeLegacy")
    String eventTypeLegacy ();

    @Key("accountsMatchingGameName")
    String accountsMatchingGameName (String arg0);

    @Key("neverLoggedOn")
    String neverLoggedOn ();

    @Key("open")
    String open ();

    @Key("enterWarningMessageForThisAccount")
    String enterWarningMessageForThisAccount ();

    @Key("findingRelatedAccounts")
    String findingRelatedAccounts ();

    @Key("hours")
    String hours ();

    @Key("filed")
    String filed ();

    @Key("accountName")
    String accountName ();

    @Key("passwordTooShort")
    String passwordTooShort ();

    @Key("errMustSelectCharacter")
    String errMustSelectCharacter ();

    @Key("accountsRelatedToAccount")
    String accountsRelatedToAccount (String arg0, String arg1);

    @Key("accountCreateTitle")
    String accountCreateTitle ();

    @Key("showEventsWithFailedResponses")
    String showEventsWithFailedResponses ();

    @Key("status")
    String status ();

    @Key("isTempBanned")
    String isTempBanned (String arg0);

    @Key("eventTypeLabel")
    String eventTypeLabel ();

    @Key("searching")
    String searching ();

    @Key("faqEditPart1")
    String faqEditPart1 ();

    @Key("noMachineIdent")
    String noMachineIdent ();

    @Key("updateWarning")
    String updateWarning ();

    @Key("mine")
    String mine ();

    @Key("owner")
    String owner ();

    @Key("lastPlayed")
    String lastPlayed ();

    @Key("enterCategoryName")
    String enterCategoryName ();

    @Key("filedBy")
    String filedBy ();

    @Key("supportHistory")
    String supportHistory ();

    @Key("returnToPetitions")
    String returnToPetitions ();

    @Key("affiliate")
    String affiliate ();

    @Key("redirecting")
    String redirecting ();

    @Key("loginFailed")
    String loginFailed ();

    @Key("errNoMessage")
    String errNoMessage ();

    @Key("languageLabel")
    String languageLabel ();

    @Key("messagePosted")
    String messagePosted ();

    @Key("dayHdr")
    String dayHdr ();

    @Key("loadingEvent")
    String loadingEvent (String arg0);

    @Key("loggingOut")
    String loggingOut ();

    @Key("admin")
    String admin ();

    @Key("petNoOpenPetitionsWereFound")
    String petNoOpenPetitionsWereFound ();

    @Key("petPostNewReply")
    String petPostNewReply ();

    @Key("fmtFirstResponse")
    String fmtFirstResponse (String arg0, String arg1, String arg2);

    @Key("created")
    String created ();

    @Key("statusEscalatedAdmin")
    String statusEscalatedAdmin ();

    @Key("emailItem")
    String emailItem ();

    @Key("maintainer")
    String maintainer ();

    @Key("billingTrial")
    String billingTrial ();

    @Key("lastUpdated")
    String lastUpdated ();

    @Key("failedEvents")
    String failedEvents ();

    @Key("petitionInstructionsInGame")
    String petitionInstructionsInGame (String arg0);

    @Key("isBanned")
    String isBanned (String arg0);

    @Key("postNoteHeaderOpen")
    String postNoteHeaderOpen ();

    @Key("enterAReasonForTheBan")
    String enterAReasonForTheBan ();

    @Key("flags")
    String flags ();

    @Key("petPost")
    String petPost ();

    @Key("jrSupport")
    String jrSupport ();

    @Key("clearIdents")
    String clearIdents ();

    @Key("result")
    String result ();

    @Key("statusIgnoredClosed")
    String statusIgnoredClosed ();

    @Key("viewIdent")
    String viewIdent ();

    @Key("filedAgainst")
    String filedAgainst ();

    @Key("eventTypeNote")
    String eventTypeNote ();

    @Key("returnToEditFaqs")
    String returnToEditFaqs ();

    @Key("eventsLabel")
    String eventsLabel ();

    @Key("relAccIdentHdr")
    String relAccIdentHdr ();

    @Key("untaintMachineIdent")
    String untaintMachineIdent ();

    @Key("viewAccount")
    String viewAccount ();

    @Key("days")
    String days ();

    @Key("insider")
    String insider ();

    @Key("noAccountsFoundMatchingGameName")
    String noAccountsFoundMatchingGameName (String arg0);

    @Key("submitPetition")
    String submitPetition ();

    @Key("accountCreatedEmail")
    String accountCreatedEmail ();

    @Key("qualifiedScore")
    String qualifiedScore ();

    @Key("petitions")
    String petitions ();

    @Key("setWaitForPlayerTip")
    String setWaitForPlayerTip ();

    @Key("accountNotFoundWithName")
    String accountNotFoundWithName (String arg0);

    @Key("messageLabel")
    String messageLabel ();

    @Key("change")
    String change ();

    @Key("warningUpdated")
    String warningUpdated ();

    @Key("edit")
    String edit ();

    @Key("eventId")
    String eventId ();

    @Key("assignEventTo")
    String assignEventTo ();

    @Key("notePosted")
    String notePosted ();

    @Key("agentActivity")
    String agentActivity ();

    @Key("cancelledWarning")
    String cancelledWarning ();

    @Key("subjectLabel")
    String subjectLabel ();

    @Key("noEventsFound")
    String noEventsFound ();

    @Key("editFlagsMessage")
    String editFlagsMessage (String arg0);

    @Key("brokenLink")
    String brokenLink ();

    @Key("reportsTitle")
    String reportsTitle ();

    @Key("loading")
    String loading ();

    @Key("claim")
    String claim ();

    @Key("agentActivityTitle")
    String agentActivityTitle ();

    @Key("name")
    String name ();

    @Key("statusOpen")
    String statusOpen ();

    @Key("banAccount")
    String banAccount ();

    @Key("search")
    String search ();

    @Key("showInactiveAccts")
    String showInactiveAccts ();

    @Key("postReply")
    String postReply ();

    @Key("petitionsAndComplaints")
    String petitionsAndComplaints ();

    @Key("falseValue")
    String falseValue ();

    @Key("updatedDate")
    String updatedDate ();

    @Key("noAccountsFoundMatchingEmail")
    String noAccountsFoundMatchingEmail (String arg0);

    @Key("noResponse")
    String noResponse ();

    @Key("warningSet")
    String warningSet ();

    @Key("firstPlayed")
    String firstPlayed ();

    @Key("recentEventVolumeTitle")
    String recentEventVolumeTitle ();

    @Key("daysItem")
    String daysItem ();

    @Key("tempBanned")
    String tempBanned ();

    @Key("petReplyToPetition")
    String petReplyToPetition (String arg0);

    @Key("firstResponse")
    String firstResponse ();

    @Key("notes")
    String notes ();

    @Key("update")
    String update ();

    @Key("submit")
    String submit ();

    @Key("responseTime")
    String responseTime ();

    @Key("generate")
    String generate ();

    @Key("standaloneLink")
    String standaloneLink ();

    @Key("loggingIn")
    String loggingIn ();

    @Key("youMustBeLoggedIn")
    String youMustBeLoggedIn ();

    @Key("postNoteHeader")
    String postNoteHeader ();

    @Key("gameName")
    String gameName ();

    @Key("eventTypeComplaint")
    String eventTypeComplaint ();

    @Key("errEnterQuery")
    String errEnterQuery ();

    @Key("chatHistory")
    String chatHistory ();

    @Key("petitionSubmitted")
    String petitionSubmitted ();

    @Key("postNoteBtn")
    String postNoteBtn ();

    @Key("questionSubmitted")
    String questionSubmitted ();

    @Key("statusInProgress")
    String statusInProgress ();

    @Key("noRelatedAccountsFoundForAccountId")
    String noRelatedAccountsFoundForAccountId (String arg0);

    @Key("waitingForPlayerLabel")
    String waitingForPlayerLabel ();

    @Key("recentEventVolume")
    String recentEventVolume ();

    @Key("qualifiedEvents")
    String qualifiedEvents ();

    @Key("addNew")
    String addNew ();

    @Key("tester")
    String tester ();

    @Key("ipAddresses")
    String ipAddresses ();

    @Key("complaints")
    String complaints ();

    @Key("eventTypes")
    String eventTypes ();

    @Key("machineIdent")
    String machineIdent ();

    @Key("warning")
    String warning ();

    @Key("updateTempBan")
    String updateTempBan ();

    @Key("menuTitleOpened")
    String menuTitleOpened ();

    @Key("eventTypeHeader")
    String eventTypeHeader ();

    @Key("category")
    String category ();

    @Key("showMessagesToPlayerWarning")
    String showMessagesToPlayerWarning ();

    @Key("returnToView")
    String returnToView ();

    @Key("trueValue")
    String trueValue ();

    @Key("setWaitForPlayer")
    String setWaitForPlayer ();

    @Key("accountId")
    String accountId ();

    @Key("postNote")
    String postNote ();

    @Key("billingFailure")
    String billingFailure ();

    @Key("volumePrefix")
    String volumePrefix ();

    @Key("noIpAddress")
    String noIpAddress ();

    @Key("accountCreateButton")
    String accountCreateButton ();

    @Key("selectCharacter")
    String selectCharacter ();

    @Key("passwordLabel")
    String passwordLabel ();

    @Key("statusEscalatedLead")
    String statusEscalatedLead ();

    @Key("advanced")
    String advanced ();

    @Key("unbanMachineIdent")
    String unbanMachineIdent ();

    @Key("warn")
    String warn ();

    @Key("accountEnabled")
    String accountEnabled ();

    @Key("cancelTempBan")
    String cancelTempBan ();

    @Key("taintMachineIdent")
    String taintMachineIdent ();

    @Key("tempBanDaysMustBePositiveNumber")
    String tempBanDaysMustBePositiveNumber ();

    @Key("selectOrCreateNewCategory")
    String selectOrCreateNewCategory ();

    @Key("advancedEventSearch")
    String advancedEventSearch ();

    @Key("anErrorOccurred")
    String anErrorOccurred (String arg0);

    @Key("clearWarning")
    String clearWarning ();

    @Key("enterQuestion")
    String enterQuestion ();

    @Key("createCategory")
    String createCategory ();

    @Key("ignoreSelected")
    String ignoreSelected ();

    @Key("gameInfo")
    String gameInfo ();

    @Key("logout")
    String logout ();

    @Key("faqEditAddQuestion")
    String faqEditAddQuestion ();

    @Key("petitionInstructionsEmail")
    String petitionInstructionsEmail (String arg0);

    @Key("deadBeat")
    String deadBeat ();

    @Key("billingBanned")
    String billingBanned ();

    @Key("login")
    String login ();

    @Key("ticketLanguage")
    String ticketLanguage ();

    @Key("statusPlayerClosed")
    String statusPlayerClosed ();

    @Key("billingStatus")
    String billingStatus ();

    @Key("enterPetitionMessage")
    String enterPetitionMessage ();

    @Key("cancel")
    String cancel ();

    @Key("passwordUpdated")
    String passwordUpdated ();

    @Key("loadedRelatedAccounts")
    String loadedRelatedAccounts ();

    @Key("cancelledTempBan")
    String cancelledTempBan ();

    @Key("billingExSubscriber")
    String billingExSubscriber ();

    @Key("petitionDefaultRecipient")
    String petitionDefaultRecipient ();

    @Key("logoutFailed")
    String logoutFailed ();

    @Key("postMessageSubtitleAgainst")
    String postMessageSubtitleAgainst (String arg0, String arg1);

    @Key("support")
    String support ();

    @Key("totalEventsReported")
    String totalEventsReported ();

    @Key("bigSpender")
    String bigSpender ();

    @Key("accountEmail")
    String accountEmail ();

    @Key("petitionInstructions2")
    String petitionInstructions2 ();

    @Key("petStatusLabel")
    String petStatusLabel ();

    @Key("searchLabel")
    String searchLabel ();

    @Key("lastUpdatedHeader")
    String lastUpdatedHeader ();

    @Key("username")
    String username ();

    @Key("enterPetitionSubject")
    String enterPetitionSubject ();

    @Key("accountCreatePassword")
    String accountCreatePassword ();

    @Key("postNoteToAccount")
    String postNoteToAccount (String arg0);

    @Key("accountCreateUsername")
    String accountCreateUsername ();

    @Key("ownerId")
    String ownerId ();

    @Key("postReplyHeader")
    String postReplyHeader ();

    @Key("petYourRecentPetitions")
    String petYourRecentPetitions ();

    @Key("enterAnswer")
    String enterAnswer ();

    @Key("idHeader")
    String idHeader ();

    @Key("hideInactiveAccts")
    String hideInactiveAccts ();

    @Key("postMessageSubtitle")
    String postMessageSubtitle (String arg0);

    @Key("emailUpdated")
    String emailUpdated ();

    @Key("idents")
    String idents ();

    @Key("answer")
    String answer ();

    @Key("unbanAccount")
    String unbanAccount ();

    @Key("characterName")
    String characterName ();

    @Key("menuTitleClosed")
    String menuTitleClosed ();

    @Key("petReplies")
    String petReplies (String arg0);

    @Key("languageHeader")
    String languageHeader ();

    @Key("eventPanelTitle")
    String eventPanelTitle (String arg0, String arg1);

    @Key("editFaqQuestion")
    String editFaqQuestion ();

    @Key("text")
    String text ();

    @Key("postReplyHeaderOpen")
    String postReplyHeaderOpen ();

    @Key("statusHeader")
    String statusHeader ();

    @Key("waitingForPlayer")
    String waitingForPlayer ();

    @Key("isEqualTo")
    String isEqualTo ();

    @Key("editFlags")
    String editFlags ();

    @Key("pageNotFound")
    String pageNotFound ();

    @Key("hasNote")
    String hasNote ();

    @Key("billingSubscriber")
    String billingSubscriber ();

    @Key("privateBy")
    String privateBy ();

    @Key("foundOneMatchOpening")
    String foundOneMatchOpening ();

    @Key("loadingFaqs")
    String loadingFaqs ();

    @Key("loadedAccount")
    String loadedAccount ();

    @Key("isWarned")
    String isWarned (String arg0);

    @Key("eventTypePetition")
    String eventTypePetition ();

    @Key("source")
    String source ();

    @Key("successful")
    String successful (String arg0);

    @Key("banMachineIdent")
    String banMachineIdent ();

    @Key("hasBoughtCoins")
    String hasBoughtCoins ();

    @Key("volumeHdr")
    String volumeHdr ();

    @Key("billingInfo")
    String billingInfo ();

    @Key("question")
    String question ();

    @Key("subject")
    String subject ();

    @Key("statusResolvedClosed")
    String statusResolvedClosed ();

    @Key("noWarning")
    String noWarning ();

    @Key("tempBan")
    String tempBan ();

    @Key("youDontHavePermission")
    String youDontHavePermission ();

    @Key("all")
    String all ();

    @Key("creationDate")
    String creationDate ();

    @Key("editFaqs")
    String editFaqs ();

    @Key("target")
    String target ();

    @Key("accountBanned")
    String accountBanned ();

    @Key("hasBoughtTime")
    String hasBoughtTime ();

    @Key("view")
    String view ();

    @Key("registered")
    String registered ();

    @Key("firstResponseTitle")
    String firstResponseTitle ();

    @Key("eventType")
    String eventType ();

    @Key("loggedInAs")
    String loggedInAs ();

    @Key("messagePostedButNotSent")
    String messagePostedButNotSent (String arg0);

    @Key("noEventFoundWithId")
    String noEventFoundWithId (String arg0);

    @Key("petRefresh")
    String petRefresh ();

    @Key("assign")
    String assign ();
}
